# -*- coding: utf-8 -*-
"""HPP_Environment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ig1j8hjXSivnVUO4ePrbQ1XMK2RiSDB9

## Download data

### Subtask:
Download the `PV_load_2020_profile.csv`, `WT_load_2020_profile.csv`, and `House_load_2020_profile.csv` files from the provided GitHub link.

**Reasoning**:
I need to download three CSV files from a GitHub repository. I will construct the raw URLs for each file and use the `requests` library to download their content and save them locally.
"""

import requests

base_url = "https://raw.githubusercontent.com/fassi16/RL_MS_Thesis/main/data/data_testing/scenario_datasets/"
files_to_download = [
    "PV_load_2020_profile.csv",
    "WT_load_2020_profile.csv"
]

for file_name in files_to_download:
    url = base_url + file_name
    response = requests.get(url)

    if response.status_code == 200:
        with open(file_name, "wb") as f:
            f.write(response.content)
        print(f"Downloaded {file_name} successfully.")
    else:
        print(f"Failed to download {file_name}. Status code: {response.status_code}")

import requests

base_url = "https://raw.githubusercontent.com/fassi16/RL_MS_Thesis/main/data/data_testing/scenario_datasets/"
file_name = "households_load_profile.csv" # New file name provided by the user
url = base_url + file_name
response = requests.get(url)

if response.status_code == 200:
    with open(file_name, "wb") as f:
        f.write(response.content)
    print(f"Downloaded {file_name} successfully.")
else:
    print(f"Failed to download {file_name}. Status code: {response.status_code}")

"""# Task
Develop a reinforcement learning environment in Python for a 100MW hybrid power plant, incorporating real-time solar and wind profiles from CSV files ("solar_profile.csv", "wind_profile.csv"), a battery storage system with a total capacity of 1000kWh, 2 hours of backup at a minimum of 200kWh, and grid interaction. The environment should include defined action and observation spaces suitable for training an RL agent to manage the power plant.
"""

import pandas as pd
import numpy as np
import gymnasium as gym
import os
import matplotlib.pyplot as plt

# Define the environment classes again to ensure they are available and updated
class HybridPowerPlant:
    def __init__(self, total_capacity_mw):
        self.total_capacity_mw = total_capacity_mw
        self.components = {}

    def add_component(self, name, capacity_mw, type):
        if name in self.components:
            print(f"Warning: Component '{name}' already exists. Overwriting.")
        self.components[name] = {'capacity_mw': capacity_mw, 'type': type}
        print(f"Added component: {name} ({type}) with capacity {capacity_mw} MW")

    def get_total_installed_capacity(self):
        total_installed = sum(comp['capacity_mw'] for comp in self.components.values())
        return total_installed

    def get_current_power_output(self, current_solar_mw, current_wind_mw):
        """Calculates total renewable power output."""
        return current_solar_mw + current_wind_mw


class BatteryStorage:
    def __init__(self, total_capacity_kwh=1000, min_backup_kwh=200, max_charge_rate_mw=50, max_discharge_rate_mw=50, charging_efficiency=0.95, discharging_efficiency=0.95):
        self.total_capacity_kwh = total_capacity_kwh
        self.current_soc_kwh = 0 # Initialize State of Charge (SOC)
        self.min_backup_kwh = min_backup_kwh
        self.max_charge_rate_mw = max_charge_rate_mw
        self.max_discharge_rate_mw = max_discharge_rate_mw
        self.charging_efficiency = charging_efficiency
        self.discharging_efficiency = discharging_efficiency
        self.E_batt = total_capacity_kwh # Rated energy of the battery
        self.soc_min = min_backup_kwh / total_capacity_kwh * 100 # Minimum SOC percentage (from min_backup_kwh)
        self.soc_max = 100.0 # Maximum SOC percentage

    def charge(self, power_mw, duration_hours=1):
        """
        Attempts to charge the battery with the given power.
        Returns the actual power charged and the updated SOC.
        """
        # Convert power from MW to MWh for current hour
        power_mwh = power_mw * duration_hours

        # Calculate potential SOC increase
        potential_soc_increase_kwh = power_mwh * 1000 * self.charging_efficiency

        # Check for maximum charge rate constraint
        max_charge_allowed_kwh = self.max_charge_rate_mw * 1000 * duration_hours
        actual_charge_kwh_rate_limited = min(potential_soc_increase_kwh, max_charge_allowed_kwh)

        # Check for total capacity constraint
        available_capacity_kwh = self.total_capacity_kwh - self.current_soc_kwh
        actual_charge_kwh = min(actual_charge_kwh_rate_limited, available_capacity_kwh)

        self.current_soc_kwh += actual_charge_kwh

        # Ensure SOC does not exceed max
        self.current_soc_kwh = min(self.current_soc_kwh, self.total_capacity_kwh)

        actual_power_charged_mw = actual_charge_kwh / (1000 * duration_hours)

        return actual_power_charged_mw

    def discharge(self, power_mw, duration_hours=1):
        """
        Attempts to discharge the battery with the given power.
        Returns the actual power discharged and the updated SOC.
        """
        # Convert power from MW to MWh for current hour
        power_mwh = power_mw * duration_hours

        # Calculate potential SOC decrease
        potential_soc_decrease_kwh = power_mwh * 1000 / self.discharging_efficiency

        # Check for maximum discharge rate constraint
        max_discharge_allowed_kwh = self.max_discharge_rate_mw * 1000 * duration_hours
        actual_discharge_kwh_rate_limited = min(potential_soc_decrease_kwh, max_discharge_allowed_kwh)

        # Check for minimum backup (SOC min) constraint
        dischargeable_energy_kwh = self.current_soc_kwh - self.min_backup_kwh
        actual_discharge_kwh = min(actual_discharge_kwh_rate_limited, dischargeable_energy_kwh)

        if actual_discharge_kwh < 0: # Cannot discharge if below min_backup_kwh or empty
            actual_discharge_kwh = 0

        self.current_soc_kwh -= actual_discharge_kwh

        # Ensure SOC does not go below 0 (or min_backup_kwh conceptually handled above)
        self.current_soc_kwh = max(self.current_soc_kwh, 0)

        actual_power_discharged_mw = actual_discharge_kwh / (1000 * duration_hours)

        return actual_power_discharged_mw

    def get_current_soc(self):
        return self.current_soc_kwh

    def get_available_charge_capacity(self):
        return self.total_capacity_kwh - self.current_soc_kwh

    def get_available_discharge_capacity(self):
        return max(0, self.current_soc_kwh - self.min_backup_kwh)


class HybridPowerPlantEnv(gym.Env):
    def __init__(self, total_plant_capacity_mw=100, battery_capacity_kwh=1000, battery_min_backup_kwh=200, battery_max_charge_mw=50, battery_max_discharge_mw=50, charging_efficiency=0.95, discharging_efficiency=0.95, max_grid_export_mw=100, system_loss_mw_per_hour=1.0, w1_renewable_utilization_reward=0.1, penalty_curtailment=1.0, simulation_duration_hours=8760, num_discrete_actions=5, n_bins_time=24, n_bins_soc=3, n_bins_power=3, n_bins_load=3, n_bins_pnet=3): # Set duration to a full year
        super().__init__()

        self.total_plant_capacity_mw = total_plant_capacity_mw
        self.simulation_duration_hours = simulation_duration_hours # Tentative duration, will be adjusted
        self.current_time_step = 0

        self.plant = HybridPowerPlant(total_capacity_mw=self.total_plant_capacity_mw)
        self.plant.add_component('SolarFarm', capacity_mw=60, type='solar')
        self.plant.add_component('WindTurbines', capacity_mw=40, type='wind')
        # Battery component is added for capacity tracking, but now it will be active
        self.plant.add_component('Battery', capacity_mw=battery_max_charge_mw, type='battery')

        self.battery = BatteryStorage(total_capacity_kwh=battery_capacity_kwh,
                                      min_backup_kwh=battery_min_backup_kwh,
                                      max_charge_rate_mw=battery_max_charge_mw,
                                      max_discharge_rate_mw=battery_max_discharge_mw,
                                      charging_efficiency=charging_efficiency,
                                      discharging_efficiency=discharging_efficiency)

        self.solar_profile = None
        self.wind_profile = None
        self.load_profile = None
        self._load_and_process_profiles() # Load data here

        # Adjust simulation duration based on loaded data
        if self.solar_profile is not None and self.wind_profile is not None and self.load_profile is not None:
             min_len = min(len(self.solar_profile), len(self.wind_profile), len(self.load_profile))
             if min_len < self.simulation_duration_hours:
                  print(f"Warning: Loaded data shorter than requested simulation duration ({min_len} vs {self.simulation_duration_hours}). Adjusting simulation duration.")
                  self.simulation_duration_hours = min_len
        else:
             # If any profile failed to load, use a small default duration
             self.simulation_duration_hours = 24
             print(f"Warning: One or more data profiles failed to load or are empty. Using default simulation duration of {self.simulation_duration_hours} hours.")


        # Convert DataFrames to dictionaries after finalizing length
        if self.solar_profile is not None:
             # Reset index to 0-based integers before converting to dict
             self.solar_profile = self.solar_profile.reset_index(drop=True)
             self.solar_profile_dict = self.solar_profile.to_dict('index')
        else:
             self.solar_profile_dict = {i: {'solar_power_MW': 0.0} for i in range(self.simulation_duration_hours)}

        if self.wind_profile is not None:
             # Reset index to 0-based integers before converting to dict
             self.wind_profile = self.wind_profile.reset_index(drop=True)
             self.wind_profile_dict = self.wind_profile.to_dict('index')
        else:
             self.wind_profile_dict = {i: {'wind_power_MW': 0.0} for i in range(self.simulation_duration_hours)}

        if self.load_profile is not None:
             # Reset index to 0-based integers before converting to dict
             self.load_profile = self.load_profile.reset_index(drop=True)
             self.load_profile_dict = self.load_profile.to_dict('index')
        else:
             self.load_profile_dict = {i: {'load_mw': 0.0} for i in range(self.simulation_duration_hours)}


        # Determine max possible renewable output and load for observation space
        max_solar = self.solar_profile['solar_power_MW'].max() if self.solar_profile is not None and not self.solar_profile.empty else self.plant.components['SolarFarm']['capacity_mw']
        max_wind = self.wind_profile['wind_power_MW'].max() if self.wind_profile is not None and not self.wind_profile.empty else self.plant.components['WindTurbines']['capacity_mw']
        max_load = self.load_profile['load_mw'].max() if self.load_profile is not None and not self.load_profile.empty else 200

        # Define bounds for P_net(t) = P_PV(t) + P_wind(t) - P_load(t)
        min_p_net = -(max_load) # Max possible deficit: 0 renewable - max load
        max_p_net = max_solar + max_wind # Max possible surplus: max renewable - 0 load

        # Store continuous observation space bounds for binning
        self.low_obs_continuous = np.array([
            0, # time_step
            0.0, # battery_soc_kwh (min SOC)
            0.0, # solar_power_mw
            0.0, # wind_power_mw
            0.0, # grid_demand_mw (which is now load)
            min_p_net # P_net(t)
        ], dtype=np.float32)
        self.high_obs_continuous = np.array([
            self.simulation_duration_hours - 1, # time_step
            self.battery.total_capacity_kwh, # battery_soc_kwh (Max possible SOC)
            max_solar, # solar_power_mw
            max_wind, # wind_power_mw
            max_load, # grid_demand_mw (load)
            max_p_net # P_net(t)
        ], dtype=np.float32)

        # Define number of bins for each observation component
        self.n_bins_time = n_bins_time
        self.n_bins_soc = n_bins_soc
        self.n_bins_power = n_bins_power
        self.n_bins_load = n_bins_load
        self.n_bins_pnet = n_bins_pnet

        # Create bins for each continuous observation variable
        self.bins_time = np.linspace(self.low_obs_continuous[0], self.high_obs_continuous[0], self.n_bins_time + 1)[1:-1]
        self.bins_soc = np.linspace(self.low_obs_continuous[1], self.high_obs_continuous[1], self.n_bins_soc + 1)[1:-1]
        self.bins_solar = np.linspace(self.low_obs_continuous[2], self.high_obs_continuous[2], self.n_bins_power + 1)[1:-1]
        self.bins_wind = np.linspace(self.low_obs_continuous[3], self.high_obs_continuous[3], self.n_bins_power + 1)[1:-1]
        self.bins_load = np.linspace(self.low_obs_continuous[4], self.high_obs_continuous[4], self.n_bins_load + 1)[1:-1]
        self.bins_pnet = np.linspace(self.low_obs_continuous[5], self.high_obs_continuous[5], self.n_bins_pnet + 1)[1:-1]

        # Define the new discrete observation space
        # The size of the discrete space will be the product of the number of bins for each component (bin_count + 1)
        total_discrete_states = (
            (self.n_bins_time + 1) *
            (self.n_bins_soc + 1) *
            (self.n_bins_power + 1) *
            (self.n_bins_power + 1) *
            (self.n_bins_load + 1) *
            (self.n_bins_pnet + 1)
        )
        self.observation_space = gym.spaces.Discrete(total_discrete_states)


        # Action space: Discrete values representing specific battery power commands
        self.num_discrete_actions = num_discrete_actions
        self.action_space = gym.spaces.Discrete(self.num_discrete_actions)

        # Define discrete power levels based on battery limits
        min_batt_power = -self.battery.max_discharge_rate_mw
        max_batt_power = self.battery.max_charge_rate_mw
        self.discrete_power_levels = np.linspace(min_batt_power, max_batt_power, self.num_discrete_actions)
        print(f"Discrete power levels for action space: {self.discrete_power_levels}")

        # Reward function coefficients as per the paper:
        # R(t) = w1*RRE(t) - w2*Pmismatch(t) - w3*Pgrid(t) - w4*Pcurt(t) - w5*PenaltySOC(t)
        self.w1_renewable_utilization_reward = w1_renewable_utilization_reward # w1
        self.penalty_unmet_demand = 5.0 # w2 for Pmismatch(t)
        self.cost_buy = 0.25 # w3 for Pgrid(t) (grid import penalty)
        self.penalty_curtailment = penalty_curtailment # w4 for Pcurt(t)
        self.battery_usage_cost = 0.005 # w5 for PenaltySOC(t) (as a proxy for SOC management)

        # Other parameters
        self.revenue_sell = 0.10
        self.max_grid_export_mw = max_grid_export_mw
        self.system_loss_mw_per_hour = system_loss_mw_per_hour

    def _generate_dummy_profile(self, power_col_name_suffix, default_mw_value, plant_component_capacity_mw):
        """Generates dummy data for a profile."""
        hours = np.arange(self.simulation_duration_hours)
        dummy_power = None

        if 'solar' in power_col_name_suffix.lower():
            # For solar, generate values up to the component capacity
            dummy_power = np.random.rand(self.simulation_duration_hours) * plant_component_capacity_mw
        elif 'wind' in power_col_name_suffix.lower():
            # For wind, generate values up to the component capacity
            dummy_power = np.random.rand(self.simulation_duration_hours) * plant_component_capacity_mw
        elif 'load' in power_col_name_suffix.lower():
            # For load, generate a more realistic fluctuating profile
            dummy_power = 50 + 50 * np.sin(2 * np.pi * (hours - 18) / 24)
            dummy_power = np.maximum(dummy_power, 0) # Ensure load is non-negative
        else:
            dummy_power = np.full(self.simulation_duration_hours, default_mw_value)

        dummy_df = pd.DataFrame({power_col_name_suffix: dummy_power})
        dummy_df.index = pd.to_datetime(pd.date_range(start='2020-01-01', periods=self.simulation_duration_hours, freq='h'))
        return dummy_df

    def _load_and_process_single_profile(self, file_path, power_col_name_suffix, default_mw_value, plant_component_capacity_mw):
        """
        Loads and processes a single data profile (solar, wind, or load).

        Args:
            file_path (str): The path to the CSV file.
            power_col_name_suffix (str): Suffix for the power column in MW (e.g., 'solar_power_MW').
            default_mw_value (float): Default power value for dummy data (e.g., 0.0 for solar/wind, a base load for load).
            plant_component_capacity_mw (float): Capacity of the related plant component (used for max solar/wind in dummy data).

        Returns:
            pd.DataFrame: Processed DataFrame with 'power_col_name_suffix' and a DatetimeIndex,
                          or a dummy DataFrame if loading fails.
        """
        profile_name = file_path.split('_')[0].capitalize() # e.g., 'PV' -> 'Pv', 'WT' -> 'Wt', 'households' -> 'Households'
        if profile_name == 'Pv': profile_name = 'Solar'
        if profile_name == 'Wt': profile_name = 'Wind'
        if profile_name == 'Households': profile_name = 'Load'

        try:
            # Attempt to read with multiple separators
            try:
                data_raw = pd.read_csv(file_path, header=None, sep='\t', engine='python', skiprows=1)
                # If tab-separated fails or produces only one column, try comma
                if data_raw.shape[1] < 2:
                    data_raw = pd.read_csv(file_path, header=None, sep=',', engine='python', skiprows=1)
            except Exception: # Fallback to comma if initial tab read fails completely
                data_raw = pd.read_csv(file_path, header=None, sep=',', engine='python', skiprows=1)

            print(f"Raw {profile_name.lower()} data loaded successfully from {file_path}")

            if data_raw.shape[1] >= 2:
                time_col_idx = 0
                power_col_idx = 1
                data_full = data_raw.copy()

                # Try multiple date formats
                data_full['time'] = pd.to_datetime(data_full.iloc[:, time_col_idx], errors='coerce', format='%d/%m/%Y %H:%M')
                if data_full['time'].isnull().all():
                    data_full['time'] = pd.to_datetime(data_full.iloc[:, time_col_idx], errors='coerce', infer_datetime_format=True)

                original_power_col_name = f"{power_col_name_suffix.replace('_MW', '').replace('_W', '')}_original"
                data_full[original_power_col_name] = pd.to_numeric(data_full.iloc[:, power_col_idx], errors='coerce')
                data_full = data_full.dropna(subset=['time', original_power_col_name]).copy()

                if not data_full.empty:
                    data_full = data_full.set_index('time')
                    # Scale to MW
                    if '_W' in power_col_name_suffix: # e.g., for 'load_W'
                         data_full[power_col_name_suffix] = data_full[original_power_col_name] / 1_000_000
                    else: # Assuming it's already in W or kW and needs scaling to MW
                         data_full[power_col_name_suffix] = data_full[original_power_col_name] / 1_000_000 # Default to W to MW

                    processed_profile = data_full[[power_col_name_suffix]].resample('h').mean().dropna()
                    print(f"Processed {profile_name.lower()} data length: {len(processed_profile)}")
                    print(f"{profile_name} data loaded and processed successfully.")
                    return processed_profile
                else:
                    print(f"Warning: {profile_name} data is empty after cleaning. Using dummy data.")
                    return self._generate_dummy_profile(power_col_name_suffix, default_mw_value, plant_component_capacity_mw)
            else:
                print(f"Error: {profile_name} data file does not contain enough columns to process. Using dummy data.")
                return self._generate_dummy_profile(power_col_name_suffix, default_mw_value, plant_component_capacity_mw)

        except FileNotFoundError:
            print(f"Error: {file_path} not found. Using dummy {profile_name.lower()} data.")
            return self._generate_dummy_profile(power_col_name_suffix, default_mw_value, plant_component_capacity_mw)
        except Exception as e:
            print(f"An error occurred while loading or processing the {profile_name.lower()} data: {e}. Using dummy {profile_name.lower()} data.")
            return self._generate_dummy_profile(power_col_name_suffix, default_mw_value, plant_component_capacity_mw)


    def _load_and_process_profiles(self):
        print("Loading and processing real-world data profiles...")

        # Load solar data
        solar_file_path = 'PV_load_2020_profile.csv'
        self.solar_profile = self._load_and_process_single_profile(
            file_path=solar_file_path,
            power_col_name_suffix='solar_power_MW',
            default_mw_value=0.0,
            plant_component_capacity_mw=self.plant.components['SolarFarm']['capacity_mw']
        )
        print("-" * 30)

        # Load wind data
        wind_file_path = 'WT_load_2020_profile.csv'
        self.wind_profile = self._load_and_process_single_profile(
            file_path=wind_file_path,
            power_col_name_suffix='wind_power_MW',
            default_mw_value=0.0,
            plant_component_capacity_mw=self.plant.components['WindTurbines']['capacity_mw']
        )
        print("-" * 30)

        # Load household load data
        load_file_path = 'households_load_profile.csv'
        self.load_profile = self._load_and_process_single_profile(
            file_path=load_file_path,
            power_col_name_suffix='load_mw', # Assuming raw data is W, will be converted to MW
            default_mw_value=50.0, # A reasonable base load for dummy data
            plant_component_capacity_mw=0 # Not directly applicable for load, but function requires it
        )

        # Ensure all profiles exist and have data, then find the minimum length
        profile_lengths = []
        if self.solar_profile is not None and not self.solar_profile.empty:
            profile_lengths.append(len(self.solar_profile))
        if self.wind_profile is not None and not self.wind_profile.empty:
             profile_lengths.append(len(self.wind_profile))
        if self.load_profile is not None and not self.load_profile.empty:
             profile_lengths.append(len(self.load_profile))

        if profile_lengths:
             min_len = min(profile_lengths)
             print(f"Minimum profile length after processing: {min_len}")
             self.simulation_duration_hours = min_len
             print(f"Adjusting simulation duration to: {self.simulation_duration_hours} hours.")

             # Reindex/trim all profiles to the minimum length and reset index to 0-based integers
             self.solar_profile = self.solar_profile.iloc[:min_len].reset_index(drop=True)
             self.wind_profile = self.wind_profile.iloc[:min_len].reset_index(drop=True)
             self.load_profile = self.load_profile.iloc[:min_len].reset_index(drop=True)

             # Convert trimmed and re-indexed DataFrames to dictionaries
             self.solar_profile_dict = self.solar_profile.to_dict('index')
             self.wind_profile_dict = self.wind_profile.to_dict('index')
             self.load_profile_dict = self.load_profile.to_dict('index')
        else:
             print("Error: No valid data profiles were loaded. Simulation duration set to 0.")
             self.simulation_duration_hours = 0
             self.solar_profile_dict = {}
             self.wind_profile_dict = {}
             self.load_profile_dict = {}

        print("\nProcessed Profile Heads (first 5 entries, indexed 0-based):")
        if self.solar_profile_dict:
            print("Solar Profile:")
            display(pd.DataFrame.from_dict(dict(list(self.solar_profile_dict.items())[:5]), orient='index'))
        if self.wind_profile_dict:
            print("Wind Profile:")
            display(pd.DataFrame.from_dict(dict(list(self.wind_profile_dict.items())[:5]), orient='index'))
        if self.load_profile_dict:
            print("Load Profile:")
            display(pd.DataFrame.from_dict(dict(list(self.load_profile_dict.items())[:5]), orient='index'))


    def _discretize_observation(self, obs_continuous):
        """
        Converts a continuous observation array into a single discrete integer state.
        """
        discrete_time = np.digitize(obs_continuous[0], self.bins_time)
        discrete_soc = np.digitize(obs_continuous[1], self.bins_soc)
        discrete_solar = np.digitize(obs_continuous[2], self.bins_solar)
        discrete_wind = np.digitize(obs_continuous[3], self.bins_wind)
        discrete_load = np.digitize(obs_continuous[4], self.bins_load)
        discrete_pnet = np.digitize(obs_continuous[5], self.bins_pnet)

        # Combine discrete values into a single integer state
        # This combination creates a unique integer for each discrete state tuple
        state = (
            discrete_time * ((self.n_bins_soc + 1) * (self.n_bins_power + 1) * (self.n_bins_power + 1) * (self.n_bins_load + 1) * (self.n_bins_pnet + 1)) +
            discrete_soc * ((self.n_bins_power + 1) * (self.n_bins_power + 1) * (self.n_bins_load + 1) * (self.n_bins_pnet + 1)) +
            discrete_solar * ((self.n_bins_power + 1) * (self.n_bins_load + 1) * (self.n_bins_pnet + 1)) +
            discrete_wind * ((self.n_bins_load + 1) * (self.n_bins_pnet + 1)) +
            discrete_load * (self.n_bins_pnet + 1) +
            discrete_pnet
        )
        return int(state)

    def step(self, action):
        if self.current_time_step >= self.simulation_duration_hours:
            # Return a discrete 0 state if terminated, for consistency
            return 0, 0.0, True, False, {}

        # Action is now an integer representing an index in discrete_power_levels
        desired_battery_power_mw = self.discrete_power_levels[action]

        # Get current renewable generation and load from profiles using 0-based index
        current_solar_data = self.solar_profile_dict.get(self.current_time_step, {'solar_power_MW': 0.0})
        current_wind_data = self.wind_profile_dict.get(self.current_time_step, {'wind_power_MW': 0.0})
        current_load_data = self.load_profile_dict.get(self.current_time_step, {'load_mw': 0.0})

        solar_power_mw_available = current_solar_data.get('solar_power_MW', 0.0)
        wind_power_mw_available = current_wind_data.get('wind_power_MW', 0.0)
        current_load_mw = current_load_data.get('load_mw', 0.0)

        renewable_output_mw = solar_power_mw_available + wind_power_mw_available

        # Initialize variables for grid interaction and battery status
        power_bought_mw = 0
        power_sold_mw = 0
        unmet_demand_mw = 0
        actual_battery_charge_mw = 0
        actual_battery_discharge_mw = 0
        net_battery_power_mw = 0
        power_for_load_mw = 0
        power_curtailed_mw = 0 # Initialize curtailment
        system_losses_mw = self.system_loss_mw_per_hour # System losses

        # --- Battery Operation ---
        if desired_battery_power_mw > 0: # Agent wants to charge
            actual_battery_charge_mw = self.battery.charge(desired_battery_power_mw)
            net_battery_power_mw = -actual_battery_charge_mw # Charging is a load on the system
        elif desired_battery_power_mw < 0: # Agent wants to discharge
            actual_battery_discharge_mw = self.battery.discharge(abs(desired_battery_power_mw))
            net_battery_power_mw = actual_battery_discharge_mw # Discharging adds power to the system

        # Total power available before considering system losses
        total_available_power_before_losses = renewable_output_mw + net_battery_power_mw

        # Apply system losses. Losses are a demand that must be met.
        effective_power_after_losses = total_available_power_before_losses - system_losses_mw

        # --- Grid Interaction ---
        # Now, calculate net power after renewables, battery, and system losses, before meeting load
        net_power_after_losses_and_battery = effective_power_after_losses - current_load_mw

        if net_power_after_losses_and_battery >= 0:
            # Surplus or exact match after meeting load
            potential_power_to_grid = net_power_after_losses_and_battery

            # Apply grid export limit
            power_sold_mw = min(potential_power_to_grid, self.max_grid_export_mw)
            power_curtailed_mw = potential_power_to_grid - power_sold_mw # Calculate curtailed power

            power_for_load_mw = current_load_mw
        else:
            # Deficit after meeting load
            deficit_to_meet = -net_power_after_losses_and_battery
            power_bought_mw = deficit_to_meet
            unmet_demand_mw = deficit_to_meet # This amount is bought to cover demand
            power_for_load_mw = current_load_mw

        # --- Reward Calculation (Aligned with R(t) = w1*RRE(t) - w2*Pmismatch(t) - w3*Pgrid(t) - w4*Pcurt(t) - w5*PenaltySOC(t)) ---
        # w1*RRE(t): Reward for renewable energy utilization (based on actual renewable output)
        reward_rre_term = self.w1_renewable_utilization_reward * renewable_output_mw

        # w2*Pmismatch(t): Penalty for power mismatch (unmet demand)
        penalty_mismatch_term = self.penalty_unmet_demand * unmet_demand_mw

        # w3*Pgrid(t): Penalty for grid utilization/reliance (power bought from grid)
        penalty_grid_reliance_term = self.cost_buy * power_bought_mw

        # w4*Pcurt(t): Penalty for renewable energy curtailment
        penalty_curtailment_term = self.penalty_curtailment * power_curtailed_mw

        # w5*PenaltySOC(t): Penalty for battery usage (as a proxy for SOC management)
        # Note: SOC limits are handled as hard constraints by the BatteryStorage class,
        # so 'violation' penalties would always be zero. This term penalizes any battery operation.
        penalty_soc_management_term = (actual_battery_charge_mw + actual_battery_discharge_mw) * self.battery_usage_cost

        # Total reward based on the formula
        reward = reward_rre_term \
                 - penalty_mismatch_term \
                 - penalty_grid_reliance_term \
                 - penalty_curtailment_term \
                 - penalty_soc_management_term

        # Additionally, include revenue from selling power to the grid as a positive incentive
        reward += power_sold_mw * self.revenue_sell

        # Increment time step BEFORE preparing next observation
        self.current_time_step += 1
        terminated = self.current_time_step >= self.simulation_duration_hours
        truncated = False

        # Prepare continuous observation for the next state
        if not terminated:
            next_solar_data = self.solar_profile_dict.get(self.current_time_step, {'solar_power_MW': 0.0})
            next_wind_data = self.wind_profile_dict.get(self.current_time_step, {'wind_power_MW': 0.0})
            next_load_data = self.load_profile_dict.get(self.current_time_step, {'load_mw': 0.0})

            next_renewable_output_mw = next_solar_data.get('solar_power_MW', 0.0) + next_wind_data.get('wind_power_MW', 0.0)
            next_net_power_balance_for_obs = next_renewable_output_mw - next_load_data.get('load_mw', 0.0)

            next_obs_continuous = np.array([
                self.current_time_step,
                self.battery.get_current_soc(),
                next_solar_data.get('solar_power_MW', 0.0),
                next_wind_data.get('wind_power_MW', 0.0),
                next_load_data.get('load_mw', 0.0),
                next_net_power_balance_for_obs
            ], dtype=np.float32)
            next_obs = self._discretize_observation(next_obs_continuous)
        else:
            next_obs = 0 # Return a discrete 0 state if terminated


        info = {
            'time_step': self.current_time_step - 1,
            'solar_power_mw': solar_power_mw_available,
            'wind_power_mw': wind_power_mw_available,
            'renewable_output_mw': renewable_output_mw,
            'battery_soc_kwh': self.battery.get_current_soc(),
            'desired_battery_power_mw': desired_battery_power_mw,
            'actual_battery_charge_mw': actual_battery_charge_mw,
            'actual_battery_discharge_mw': actual_battery_discharge_mw,
            'net_battery_power_mw': net_battery_power_mw,
            'current_load_mw': current_load_data.get('load_mw', 0.0),
            'total_available_power_before_losses_mw': total_available_power_before_losses,
            'system_losses_mw': system_losses_mw,
            'effective_power_after_losses_mw': effective_power_after_losses,
            'power_for_load_mw': power_for_load_mw,
            'power_bought_mw': power_bought_mw,
            'power_sold_mw': power_sold_mw,
            'power_curtailed_mw': power_curtailed_mw,
            'unmet_demand_mw': unmet_demand_mw,
            'reward_rre_term': reward_rre_term,
            'penalty_mismatch_term': penalty_mismatch_term,
            'penalty_grid_reliance_term': penalty_grid_reliance_term,
            'penalty_curtailment_term': penalty_curtailment_term,
            'penalty_soc_management_term': penalty_soc_management_term
        }

        return next_obs, reward, terminated, truncated, info

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        self.current_time_step = 0
        self.battery.current_soc_kwh = self.battery.min_backup_kwh # Initialize SOC to min_backup_kwh instead of 0

        initial_solar_data = self.solar_profile_dict.get(self.current_time_step, {'solar_power_MW': 0.0})
        initial_wind_data = self.wind_profile_dict.get(self.current_time_step, {'wind_power_MW': 0.0})
        initial_load_data = self.load_profile_dict.get(self.current_time_step, {'load_mw': 0.0})

        initial_renewable_output_mw = initial_solar_data.get('solar_power_MW', 0.0) + initial_wind_data.get('wind_power_MW', 0.0)
        initial_net_power_balance_for_obs = initial_renewable_output_mw - initial_load_data.get('load_mw', 0.0)

        initial_obs_continuous = np.array([
            self.current_time_step,
            self.battery.get_current_soc(),
            initial_solar_data.get('solar_power_MW', 0.0),
            initial_wind_data.get('wind_power_MW', 0.0),
            initial_load_data.get('load_mw', 0.0),
            initial_net_power_balance_for_obs
        ], dtype=np.float32)
        initial_obs = self._discretize_observation(initial_obs_continuous)

        info = {
            'battery_soc_kwh': self.battery.get_current_soc(),
            'grid_demand_mw': initial_load_data.get('load_mw', 0.0)
        }

        return initial_obs, info

    def render(self, mode='human'):
        pass

    def close(self):
        pass

"""Let's instantiate the `HybridPowerPlantEnv` and confirm its discrete observation and action spaces, then test a `reset` and `step` to see the integer states and actions."""

# Instantiate the environment with discrete observation and action spaces
env = HybridPowerPlantEnv(
    num_discrete_actions=5,
    n_bins_time=24,
    n_bins_soc=3,
    n_bins_power=3,
    n_bins_load=3,
    n_bins_pnet=3
)

print('Environment Observation Space:', env.observation_space)
print('Environment Action Space:', env.action_space)
print(f"Total possible discrete states: {env.observation_space.n}")
print(f"Discrete power levels for actions: {env.discrete_power_levels}")

# Test a reset on the discrete environment
initial_discrete_obs, info = env.reset()
print(f"\nInitial discrete observation after reset: {initial_discrete_obs}")
print(f"Info after reset: {info}")

# Test a step on the discrete environment with a sampled discrete action
discrete_action = env.action_space.sample()
print(f"\nSampled discrete action: {discrete_action} (corresponds to {env.discrete_power_levels[discrete_action]:.2f} MW)")

next_discrete_obs, reward, terminated, truncated, info = env.step(discrete_action)
print(f"Next discrete observation after step: {next_discrete_obs}")
print(f"Reward: {reward}")
print(f"Terminated: {terminated}, Truncated: {truncated}")
print(f"Info after step: {info}")

env.close()

"""Let's test the `HybridPowerPlantEnv` with its new discrete action space. We'll create an instance, inspect the action space, and perform a reset and step."""
